WITH RECURSIVE cte AS (
    SELECT 0 AS HOUR
    UNION ALL
    SELECT HOUR+1 FROM cte 
    WHERE HOUR < 23
)

SELECT b.HOUR, COUNT(a.DATETIME) as COUNT FROM ANIMAL_OUTS as a
RIGHT JOIN cte as b ON b.HOUR = HOUR(a.DATETIME)
GROUP BY b.HOUR
ORDER BY b.HOUR;

-- RECURSIVE WITH, right join!!